services:  
  backend:    
    build:      
      context: ./Backend    
    ports:      
      - "8080:8080"    
    networks:      
      - app-network    
    restart: always
  
  frontend:    
    build:      
      context: ./Frontend    
    ports:      
      - "80:80"    
    networks:      
      - app-network
    restart: always
    volumes:
      - ./Frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend 
  
networks:       
  app-network:    
    name: app-network
    driver: bridge