services:  
  backend:    
    image: ricardocr98/pico-placa-backend:latest  
    ports:      
      - "8080:8080"    
    networks:      
      - app-network    
    restart: always
  
  frontend:    
    image: ricardocr98/pico-placa-frontend:latest
    ports:      
      - "80:80"    
    networks:      
      - app-network
    volumes:
      - ./Frontend/nginx.conf:/etc/nginx/nginx.conf 
    restart: always

networks:       
  app-network:
    name: app-network
    driver: bridge